name: Rebuild Merkle Root
on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 min UTC
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: rebuild-merkle-root
  cancel-in-progress: false

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Timestamp (UTC)
        shell: bash
        run: |
          echo "UTC: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

      - name: Call /api/rebuild (debug)
        env:
          API_URL: https://mrt-nft.vercel.app/api/rebuild
          REBUILD_TOKEN: ${{ secrets.REBUILD_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
      
          echo "POST $API_URL"
          # Save headers and body separately; don't use -f so we can read the body on 500s
          curl -sS -X POST "$API_URL" \
            -H "Authorization: Bearer $REBUILD_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{}' \
            -D headers.txt \
            -o body.txt \
            -w "HTTP %{http_code}\n" | tee status.txt
      
          echo "::notice title=Rebuild status::$(cat status.txt)"
          echo "::notice title=Response headers::$(sed -e 's/%/%25/g' -e 's/\r/%0D/g' -e 's/\n/%0A/g' headers.txt)"
          echo "::notice title=Response body::$(sed -e 's/%/%25/g' -e 's/\r/%0D/g' -e 's/\n/%0A/g' body.txt)"
      
          code=$(cut -d' ' -f2 < status.txt)
          # Fail if 4xx/5xx
          if [[ "$code" -ge 400 ]]; then
            echo "Server returned HTTP $code"
            exit 22
          fi
